# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10  

  - name: Research
    identifier: research
    url: research
    weight: 20
  - name: Additive and Advanced Manufacturing, Precision Control
    parent: Research
    url: research/Additive_Advanced_Manufacturing_Precision_Control
    weight: 10
  - name: Collaborative Robots, Visual Servo, Autonomy under Limited Sensing
    parent: Research
    url: research/Collaborative_Robots_Visual_Servo
    weight: 20
  - name: Adaptive Control and Active Vibration Rejection
    parent: Research
    url: research/Adaptive_Control_Active_Vibration_Rejection
    weight: 30
  - name: Science of Robotic Inspection of Complex Reflective Parts
    parent: Research
    url: research/Science_Robotic_Inspection_Complex_Reflective_Parts
    weight: 40
  - name: Tactile Sensing for Intelligent Manipulation
    parent: Research
    url: research/Tactile_Sensing_Intelligent_Manipulation
    weight: 50
  - name: Advanced Composite Manufacturing
    parent: Research
    url: research/Advanced_Composite_Manufacturing
    weight: 60

  - name: People
    url: people
    weight: 30
  - name: Publications
    url: publication
    weight: 40
  - name: News
    url: post
    weight: 50
  - name: Outreach
    url: outreach
    weight: 60
  - name: Teaching
    url: teaching
    weight: 70 
  - name: Contact
    url: contact
    weight: 80 
  - name: Events
    url: event
    weight: 90
  - name: Tour
    url: tour
    weight: 100
